### ISSUE TITLE
Feature request: Auto-generate the GitHub Actions workflow file for CompatHelper.jl

### ISSUE THREAD

**Issue by DilumAluthge** [invenia/PkgTemplates.jl#105]
Would this be easy or difficult?

Basically, we would need to generate the file `.github/workflows/CompatHelper.yml` with the following content.

(Presumably, instead of hard-coding `1.2.0`, we would need to replace that with whatever version of Julia the user chose when creating their `Template`.)

```yaml
name: CompatHelper

on:
  schedule:
    - cron: '00 * * * *'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: [1.2.0]
        julia-arch: [x86]
        os: [ubuntu-latest]
    steps:
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.julia-version }}
      - name: Pkg.add("CompatHelper")
        run: julia -e 'using Pkg; Pkg.add("CompatHelper")'
      - name: CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: julia -e 'using CompatHelper; CompatHelper.main()'
```
