### ISSUE TITLE
Custom registry support for GitHub based CI

### ISSUE THREAD

**Issue by crstnbr** [invenia/PkgTemplates.jl#109]
As discussed in https://github.com/invenia/PkgTemplates.jl/issues/96, it would be great if the Github CI plugin would support custom registries as well.

Basically the latter simply requires an extra step in the workflow:

```yml
- name: Add CustomRegistry
  run: julia -e 'using Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="http://github.com/JuliaRegistries/General")); Pkg.Registry.add(Pkg.RegistrySpec(url="http://github.com/owner/CustomRegistry")); Pkg.Registry.status()'
  shell: bash
```

Note that one has to set `shell: bash` as otherwise Windows runs will fail. Also, one cannot test on Julia < 1.1 this way, since, as has been pointed out by @DilumAluthge in #96, the `Pkg.Registry` stuff requires Julia >= 1.1.

(See [here](https://github.com/crstnbr/TestPackage2.jl/blob/master/.github/workflows/CI.yaml) for a working example.)
