### ISSUE TITLE
CI plugins: skip PR builds for non-forks

### ISSUE THREAD

**Issue by christopher-dG** [invenia/PkgTemplates.jl#193]
There was a bit of discussion on Slack yesterday about getting GitHub Actions to skip PR builds for branches that are already being built for push events: it's redundant to run your test suite twice for every push when you have an open PR. This annoys me a bunch too, so maybe it's a sensible default to give our CI config templates.

The GitHub Actions config looks like this:

```
if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name != github.repository)
```

**Comment by DilumAluthge** [comment]
I would prefer that this not be the default behavior. 

As I posted on Slack, my preferred workflow is to not run CI on pushes to branches that aren't master:
```yaml
name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - staging
      - trying
    tags: '*'
```
