### ISSUE TITLE
Gtk mac and Linux

### ISSUE THREAD

**Issue by yakir12** [invenia/PkgTemplates.jl#2]
For applications that include `Gtk` and need to run on linux and mac the following `.travis.yml` code works for me: 
```yml
    apt:
        packages:
            - xvfb
            - xauth
            - libgtk-3-0
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD -e 'Pkg.clone(pwd()); using BinDeps; println(BinDeps.debug("Package")); Pkg.build("Package"); Pkg.test("Package"; coverage=true)'
```
Maybe you could work that into your package somehow?
