### ISSUE TITLE
Documenter via GithubActions

### ISSUE THREAD

**Issue by musm** [invenia/PkgTemplates.jl#218]
My template spits out
```
      - run: |
          julia --project=docs -e '
            using Pkg
            Pkg.develop(PackageSpec(path=pwd()))
            Pkg.instantiate()'
      - run: |
          julia --project=docs -e '
            using Documenter: doctest
            using HDF5
            doctest(HDF5)'
      - run: julia --project=docs docs/make.jl
```

Whereas I think it should be something like:

```
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.4
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
```
