### ISSUE TITLE
Adding a Docker-Workflow for Github-Action?

### ISSUE THREAD

**Issue by Anselmoo** [invenia/PkgTemplates.jl#235]
Would it not be good to support `Docker-Images `as packages via the Github-Action?
Since you already have a very powerful options for Github-Action?

```yaml
name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

```
