### ISSUE TITLE
manual setting of tokens for coverage with gh-actions

### ISSUE THREAD

**Issue by lucaferranti** [invenia/PkgTemplates.jl#279]
Hi everyone,

The documentation for [PkgTemplates.GitHubActions](https://invenia.github.io/PkgTemplates.jl/stable/user/#PkgTemplates.GitHubActions) says ` If using coverage plugins, don't forget to manually add your API tokens as secrets, as described here.` I am a little puzzled by this, based on [this issue](https://github.com/julia-actions/julia-uploadcodecov/issues/1) and [this example](https://github.com/codecov/codecov-action), I would understand this step is not needed for public repositories? 

PkgTemplates atm generates the following patch for codecov
```
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: lcov.info
```

which seems to me the same example without token for public repository? Is that note in the doc outdated or am I missing something?
