### ISSUE TITLE
Add GitHub Actions as a supported form of Continuous Integration (CI)

### ISSUE THREAD

**Issue by DilumAluthge** [invenia/PkgTemplates.jl#96]
GitHub Actions will reach general availability on November 13. It would be great if, by that date, PkgTemplates was able to set up GitHub Actions for continuous integration (CI).

Unfortunately, I know very little about GitHub Actions. But I know that @davidanthoff has been working on Julia + GitHub Actions. Maybe he can provide some guidance.

**Comment by christopher-dG** [comment]
That should be an easy deadline to hit, seeing as https://github.com/julia-actions has most of the work done.

**Comment by davidanthoff** [comment]
I think we are still trying to figure out the best way to do this with GitHub Actions, any feedback on what we have so far would be great!

**Comment by christopher-dG** [comment]
Sounds good, I'll have a look and open issues if I notice anything.

**Comment by DilumAluthge** [comment]
@christopher-dG Out of curiosity, will PR #61 fix this issue?

**Comment by crstnbr** [comment]
Since I couldn't find it in the docs, is it now possible to set up GitHub workflow based CI through PkgTemplates?

**Comment by christopher-dG** [comment]
On master branch; I need to re-add the interactive code before tagging a new release.
You can browse docs for #107 [here](https://cdg.dev/files/PkgTemplates), which is master + TagBot + CompatHelper.

**Comment by crstnbr** [comment]
AFAICS, there is no support for Github CI + custom registry, though. Basically the latter simply requires an extra step in the workflow:

```yml
- name: Add CustomRegistry
  run: julia -e 'using Pkg; Pkg.Registry.add(Pkg.RegistrySpec(url="http://github.com/JuliaRegistries/General")); Pkg.Registry.add(Pkg.RegistrySpec(url="http://github.com/owner/CustomRegistry")); Pkg.Registry.status()'
        shell: bash
```

Note that one has to set `shell: bash` as otherwise Windows runs will fail. Also, one cannot test on Julia < 1.1 this way, since, as has been pointed out by @DilumAluthge above, the `Pkg.Registry` stuff requires Julia >= 1.1.

Should I open a separate issue for this?
